
library(spliceR)

library(cummeRbund)

dbFile<-paste('cuffdiff',"/cuffData.db", sep="")

cuff<-readCufflinks('cuffdiff') ###create a database out of cuffdiff output files. 

#Generate SpliceRList from cufflinks data
cuffDB_spliceR <- prepareCuff(cuff, removeNonChanonicalChr=TRUE)
generateGTF(cuffDB_spliceR, filters=NULL, expressionCutoff=0,scoreMethod="local", filePrefix="spliceR_transcripts", shortDescription="SpliceR Transcripts", longDescription="Transcripts generated by SpliceR", useProgressBar=T)
